# Generated by Django 4.0.2 on 2022-04-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movimiento', models.CharField(choices=[('I', 'Ingreso'), ('G', 'Gasto')], max_length=1, verbose_name='Movimiento')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripcion')),
            ],
        ),
    ]
