# Generated by Django 4.0.2 on 2022-04-07 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='movimiento',
        ),
    ]
