# Generated by Django 4.0.2 on 2022-04-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_remove_datos_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='movimiento',
            field=models.CharField(choices=[('I', 'Ingreso'), ('G', 'Gasto')], max_length=1, null=True, verbose_name='Movimiento'),
        ),
    ]
