# Generated by Django 4.0.2 on 2022-04-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_datos_movimiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos',
            new_name='Informacion',
        ),
    ]
