# Generated by Django 4.0.2 on 2022-04-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0004_rename_datos_informacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informacion',
            new_name='Dato',
        ),
    ]
