# Generated by Django 4.0.2 on 2022-04-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_rename_informacion_dato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='movimiento',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], max_length=7, null=True, verbose_name='Movimiento'),
        ),
    ]
