# Generated by Django 4.0.3 on 2022-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0006_alter_dato_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripcion')),
                ('fecha_lim', models.DateField(verbose_name='Fecha_lim')),
            ],
        ),
    ]
