# Generated by Django 4.0.3 on 2022-05-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0008_dato_nombre_tercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='nombre_tercero',
            field=models.TextField(default=None, max_length=35, verbose_name='Tercero'),
        ),
    ]
