# Generated by Django 4.0.3 on 2022-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0009_alter_dato_nombre_tercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='nombre_tercero',
            field=models.TextField(default=None, error_messages={'blank': 'El tercero que ingresaste no existe'}, max_length=35, verbose_name='Tercero'),
        ),
    ]
