# Generated by Django 4.0.4 on 2022-05-30 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0010_alter_dato_nombre_tercero'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
