# Generated by Django 4.0.4 on 2022-05-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0011_dato_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
