# Generated by Django 4.0.3 on 2022-04-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_tercero', models.TextField(max_length=35, verbose_name='tipo tercero')),
                ('nombre_tercero', models.TextField(max_length=35, verbose_name='nombre tercero')),
                ('cedula_tercero', models.IntegerField(verbose_name='cedula tercero')),
                ('correo_tercero', models.EmailField(max_length=35, verbose_name='correo tercero')),
                ('celular_tercero', models.IntegerField(verbose_name='celular tercero')),
            ],
        ),
    ]
