# Generated by Django 4.0.3 on 2022-04-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='tipo_tercero',
            field=models.CharField(choices=[('proveedor', 'PROVEEDOR'), ('cliente', 'CLIENTE')], default='SELECCIONAR', max_length=10, verbose_name='tipo tercero'),
        ),
    ]
