# Generated by Django 4.0.3 on 2022-05-06 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0007_alter_tercero_tipo_tercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='celular_tercero',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')], verbose_name='celular tercero'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='tipo_tercero',
            field=models.CharField(choices=[('proveedor', 'PROVEEDOR'), ('cliente', 'CLIENTE')], default='CLIENTE', max_length=10, verbose_name='tipo tercero'),
        ),
    ]
