# Generated by Django 4.0.3 on 2022-05-06 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0008_alter_tercero_celular_tercero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='cedula_tercero',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='El celular debe de tener minimo 8 numeros', regex='^.{8}$')], verbose_name='cedula tercero'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='celular_tercero',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='El celular debe de tener minimo 10 numeros', regex='^.{10}$')], verbose_name='celular tercero'),
        ),
    ]
