# Generated by Django 4.0.3 on 2022-05-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0010_alter_tercero_cedula_tercero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='cedula_tercero',
            field=models.IntegerField(verbose_name='cedula tercero'),
        ),
    ]
