# Generated by Django 4.0.3 on 2022-04-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.TextField(max_length=35, verbose_name='nombre_cliente')),
                ('cedula_cliente', models.IntegerField(max_length=15, verbose_name='cedula_cliente')),
                ('correo_cliente', models.TextField(max_length=35, verbose_name='correo_cliente')),
                ('celular_cliente', models.IntegerField(max_length=15, verbose_name='celular_cliente')),
            ],
        ),
    ]
