# Generated by Django 4.0.3 on 2022-04-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_cedula_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula_cliente',
            field=models.IntegerField(verbose_name='cedula cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular_cliente',
            field=models.IntegerField(verbose_name='celular cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo_cliente',
            field=models.EmailField(max_length=35, verbose_name='correo cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.TextField(max_length=35, verbose_name='nombre cliente'),
        ),
    ]
